package loganalyzer.infrastructure.storage;

import java.sql.Connection;
import java.sql.SQLException;
import java.sql.Statement;

final class DatabaseSchema {
    private static final String CREATE_EVENTS_TABLE_SQL = "CREATE TABLE IF NOT EXISTS events (" +
            "id INT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) PRIMARY KEY," +
            "event_id VARCHAR(100) NOT NULL," +
            "duration INT NOT NULL," +
            "type VARCHAR(100) NULL," +
            "host VARCHAR(100) NULL," +
            "alert BOOLEAN NOT NULL," +
            ")";

    public static void create(Connection connection) throws SQLException {
        try(Statement statement = connection.createStatement()) {
            statement.execute(CREATE_EVENTS_TABLE_SQL);
        }
    }
}
